config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'home#index'
  get '/about', to: 'about#index'
  get '/area_of_practice', to: 'area_of_practice#index'
  get '/testimonials', to: 'testimonials#index'
  get '/location', to: 'location#index'
  post '/location', to: 'location#create', as: 'create_email'
  resources :users
  resources :dashboard
  resources :sessions
  resources :entries
  resources :thank_you

  post '/dashboard/handle_request', to: "dashboard#handle_request", as: "create_entry"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/email.rb
class Email < ApplicationRecord
end

app/models/entry.rb
class Entry < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  
  has_secure_password

end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
    @entry = Entry.where(category: "about")
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController

  before_filter :check_admin

  def index
    @about = Entry.where(category: "about")
    @areas_of_practice = Entry.where(category: "area_of_practice")
    @testimonials = Entry.where(category: "testimonial")
    @contact = Entry.where(category: "contact")
    @home_pages = Entry.where(category: "home-page")
  end


  def handle_request
    if params[:method] == "edit"
      @entry = Entry.find_by_id(params[:id])
      respond_to do |format|
        format.html
        format.json { render json: {:success => true, html: (render_to_string('_edit-modal.html.erb',object: @entry, layout: false))} }
      end
    else
      @entry = Entry.new
      @entry.category = params[:category]
      respond_to do |format|
        format.html
        format.json { render json: {:success => true, html: (render_to_string('_popup-modal.html.erb',object: @entry, layout: false))} }
      end
    end
  end

  private
  def check_admin
    if current_user
      unless current_user.admin
        redirect_to root_url
      end
    else
      redirect_to root_url
    end
  end

end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController

  def create
    entry = Entry.new(entry_params)
    if entry.save
      redirect_to dashboard_index_url
    end
  end

  def destroy
    entry = Entry.find_by_id(params[:id])
    entry.destroy!
    redirect_to dashboard_index_url
  end

  def update
    entry = Entry.find_by_id(params[:id])
    entry.update_attributes(updated_attributes)
    redirect_to dashboard_index_url
  end


  private

  def entry_params
    params.require(:entry).permit(:title, :description, :category)
  end

  def updated_attributes
    params.require(:entry).permit(:title, :description, :category)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @entry = Entry.find_by(category: "home-page")
  end
end

app/controllers/location_controller.rb
class LocationController < ApplicationController
  def index
    @email = Email.new
  end

  def create
    @email = Email.new(email_params)
    if @email.save
      UserNotifierMailer.send_signup_email(@email).deliver
      redirect_to thank_you_index_path
      flash[:notice] = "Email succesfully sent!"
    else
      redirect_to location_url
      flash[:notice] = "Something wen't wrong, try again."
    end

  end

  private
  def email_params
    params.require(:email).permit(:email_content, :email_address, :email_subject)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def create
    user = User.find_by('lower(username) = ?', session_params[:username].downcase)
    if user && user.authenticate(session_params[:password])
      session[:user_id] = user.id
      redirect_to dashboard_index_url
    else
      redirect_to root_url
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url
  end

  private
  def session_params
    params.require(:session).permit(:username, :password)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    user = User.new(user_params)
    if user.save
      session[:user_id] = user.id
      redirect_to dashboard_index_url
    else
      redirect_to root_url
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :password, :password_confirmation)
  end

end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def css_slug
    "#{params[:controller]}-#{params[:action]}"
  end
end

app/helpers/area_of_practice_helper.rb
module AreaOfPracticeHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/location_helper.rb
module LocationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/testimonials_helper.rb
module TestimonialsHelper
end

app/helpers/thank_you_helper.rb
module ThankYouHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/about/index.html.erb
<div class="container-fluid about-container">
  <div class="row about-row">
    <div class="col-lg-6 col-sm-12 image-div">
      <%= image_tag "pierre-resize.jpg", :class => "big-pierre img-rounded" %>
    </div>
    <div class="col-lg-6 about-text">
      <div class="about-text-detail fade-in one">
            <div class="entry-container">
              <% @entry.each do |entry| %>
                <h1 class="entry-header"><%= entry.title %></h1>
                <hr class="feature-divider-about">
                <h4 class="entry-description"><%= entry.description %></h4>
              <% end %>
            </div>
        </div>

        <!-- <div class="entry-container">
          <h1 class="entry-header">oqineioqwieounqw</h1>
          <p class="entry-description">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus imperdiet, libero eu consectetur aliquam, sapien mauris tincidunt mauris, mattis sagittis neque nisl quis justo. Donec at ante ac felis sollicitudin porttitor at sed elit. Nunc rhoncus ipsum laoreet lacus dictum dapibus cursus a neque. Sed non placerat sapien, vel finibus turpis. Integer posuere a eros id hendrerit. Nulla sed tempor mi, eget imperdiet dui. Sed molestie fringilla ligula nec commodo. Duis ut sollicitudin urna. Donec ornare malesuada maximus. Phasellus blandit eros sit amet libero hendrerit posuere. Vestibulum fringilla lacinia orci, eu varius odio condimentum in. Sed finibus diam non ullamcorper aliquam. Duis in viverra arcu, ut blandit mauris. Nunc lobortis purus ultrices massa ullamcorper congue. Nulla facilisi. Maecenas et cursus felis.</p>
        </div> -->
        <!-- <h1>Experienced</h1>
        <hr class="feature-divider-about">
        <h3 class="heading-description">With over 22 years’ experience in family law in Etobicoke, Mississauga, west Toronto, I can assist you with your family law issues. I have helped hundreds of clients resolve simple and  complex issues, through negotiations, mediation, arbitration, or litigation including trials.</h3>
        <h1>Attention to Clients</h1>
        <hr class="feature-divider-about">
        <h3 class="heading-description">Everyone faces different issues. Everyone has different goals. I listen very carefully to clients to understand their concerns and what they want. I can easily be reached by e-mail or phone and respond to e-mails or phone messages very quickly. In an emergency I can respond immediately (unless I am in a Courtroom of course). Clients are very quickly advsed of any developments on their files.</h3>
        <h1>Honest Advice</h1>
        <hr class="feature-divider-about">
        <h3 class="heading-description">Understanding the applicable laws, principles and rules is essential for clients, whether during negotiations, mediation, arbitration, or litigation. I always strive to give clients clear legal advice and direction, throughout the entire process.</h3>
        <div class="about-text-last">
          <h1>Cost-effective Resolution</h1>
          <hr class="feature-divider-about">
          <h3 class="heading-description">I always strive to develop the most cost-effective approach towards resolving issues, always in consultation with clients.  I encourage client to save costs and to perform tasks that do not require the assistance of a lawyer or a law clerk.</h3>
        </div> -->
      </div>
    </div>
  </div>
</div>
<div class="home-footer-testimonial">
  <p class="footer-text-testimonial">
    ©Pierre Sicco.Disclaimer/Terms of Use | Sitemap | 5464 Dundas St. W., Suite 302 Etobicoke, ON | 416-231-6555 Ext: 241
  </p>
</div>

app/views/dashboard/_about.html.erb
<div class="add-button-container">
  <%= button_tag "+", class:"btn btn-primary add-button", id:"about" %>
</div>
<table class="table">
  <thead>
    <tr>
      <th>#</th>
      <th>Title</th>
      <th>Description</th>
      <th>Edit</th>
      <th>Delete</th>
    </tr>
  </thead>
  <tbody>
    <% @about.each_with_index do |a, index| %>
    <tr>
      <th scope="row"><%= index + 1 %></th>
      <td><%= a.title %></td>
      <td><%= a.description %></td>
      <td><%= button_tag "Edit", class:"btn btn-primary edit-button", id:"#{a.id}" %></td>
      <td><%= button_to "Delete", entry_url(a.id), method: :delete, class:"btn btn-primary delete-button" %></td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/dashboard/_area-of-practice.html.erb
<div class="add-button-container">
  <%= button_tag "+", class:"btn btn-primary add-button", id:"area_of_practice" %>
</div>
<table class="table">
  <thead>
    <tr>
      <th>#</th>
      <th>Title</th>
      <th>Description</th>
      <th>Edit</th>
      <th>Delete</th>
    </tr>
  </thead>
  <tbody>
    <% @areas_of_practice.each_with_index do |a, index| %>
    <tr>
      <th scope="row"><%= index + 1 %></th>
      <td><%= a.title %></td>
      <td><%= a.description %></td>
      <td><%= button_tag "Edit", class:"btn btn-primary edit-button", id:"#{a.id}" %></td>
      <td><%= button_to "Delete", entry_url(a.id), method: :delete, class:"btn btn-primary delete-button" %></td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/dashboard/_contact.html.erb
<div class="add-button-container">
  <%= button_tag "+", class:"btn btn-primary add-button", id: "contact" %>
</div>
<table class="table">
  <thead>
    <tr>
      <th>#</th>
      <th>Title</th>
      <th>Description</th>
      <th>Edit</th>
      <th>Delete</th>
    </tr>
  </thead>
  <tbody>
    <% @contact.each_with_index do |a, index| %>
    <tr>
      <th scope="row"><%= index + 1 %></th>
      <td><%= a.title %></td>
      <td><%= a.description %></td>
      <td><%= button_tag "Edit", class:"btn btn-primary edit-button", id:"#{a.id}" %></td>
      <td><%= button_to "Delete", entry_url(a.id), method: :delete, class:"btn btn-primary delete-button" %></td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/dashboard/_edit-modal.html.erb
<!-- <div class="modal-container">
  <div class="modal-contents">

  </div>
</div> -->
<div class="modal fade">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title"><%= "#{@entry.category} entry" %></h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%= form_for @entry, url: entry_url(@entry.id), method: "patch" do |f| %>
        <div class="form-group">
          <%= f.text_field :title, class:"form-control", placeholder: "Title" %>
        </div>
        <div class="form-group">
          <%= f.text_area :description, class:"form-control", placeholder: "Description"  %>
        </div>
        <div class="form-group">
          <%= f.text_field :category, class:"form-control", text: "#{@entry.category}", readonly: true%>
        </div>
        <%= f.submit "Save Edit", class:"btn btn-primary" %>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/dashboard/_home-page.html.erb
<div class="add-button-container">
  <%= button_tag "+", class:"btn btn-primary add-button", id:"home-page" %>
</div>
<table class="table">
  <thead>
    <tr>
      <th>#</th>
      <th>Title</th>
      <th>Description</th>
      <th>Edit</th>
      <th>Delete</th>
    </tr>
  </thead>
  <tbody>
    <% @home_pages.each_with_index do |a, index| %>
    <tr>
      <th scope="row"><%= index + 1 %></th>
      <td><%= a.title %></td>
      <td><%= a.description %></td>
      <td><%= button_tag "Edit", class:"btn btn-primary edit-button", id:"#{a.id}" %></td>
      <td><%= button_to "Delete", entry_url(a.id), method: :delete, class:"btn btn-primary delete-button" %></td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/dashboard/_popup-modal.html.erb
  <!-- <div class="modal-container">
    <div class="modal-contents">

    </div>
  </div> -->
  <div class="modal fade">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title"><%= "#{@entry.category} entry" %></h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <%= form_for @entry, url: entries_url, method: "post" do |f| %>
          <div class="form-group">
            <%= f.text_field :title, class:"form-control", placeholder: "Title" %>
          </div>
          <div class="form-group">
            <%= f.text_area :description, class:"form-control", placeholder: "Description"  %>
          </div>
          <div class="form-group">
            <%= f.text_field :category, class:"form-control", text: "#{@entry.category}", readonly: true%>
          </div>
          <%= f.submit "Save", class:"btn btn-primary" %>

        </div>

        <% end %>

      </div>
    </div>
  </div>

app/views/dashboard/_testimonials.html.erb
<div class="add-button-container">
  <%= button_tag "+", class:"btn btn-primary add-button", id: "testimonial" %>
</div>
<table class="table">
  <thead>
    <tr>
      <th>#</th>
      <th>Title</th>
      <th>Description</th>
      <th>Edit</th>
      <th>Delete</th>
    </tr>
  </thead>
  <tbody>
    <% @testimonials.each_with_index do |a, index| %>
    <tr>
      <th scope="row"><%= index + 1 %></th>
      <td><%= a.title %></td>
      <td><%= a.description %></td>
      <td><%= button_tag "Edit", class:"btn btn-primary edit-button" %></td>
      <td><%= button_to "Delete", entry_url(a.id), method: :delete, class:"btn btn-primary delete-button" %></td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/dashboard/index.html.erb
<div class="dashboard-container">
  <ul class="nav nav-tabs">
    <li class="active"><a data-toggle="tab" href="#about">About</a></li>
    <li><a data-toggle="tab" href="#practice">Area of Practice</a></li>
    <li><a data-toggle="tab" href="#testimonials">Testimonials</a></li>
    <li><a data-toggle="tab" href="#home-page">Home Page</a></li>

  </ul>
  <div class="tab-content">
    <div id="about" class="tab-pane fade in active">
      <%= render "about" %>
    </div>
    <div id="practice" class="tab-pane fade">
      <%= render "area-of-practice" %>
    </div>
    <div id="testimonials" class="tab-pane fade">
      <%= render "testimonials" %>

    </div>

    <div id="home-page" class="tab-pane fade">
      <%= render "home-page" %>
    </div>
  </div>
</div>

app/views/home/index.html.erb
<div class="container-fluid container-homepage">
  <div class="row vertical-center-row">
    <div class="col-lg-6 col-lg-offset-6 homepage-text">
      <h1 class="main-title fade-in one"><%= @entry.title %></h1>
      <h2 class="sub-title fade-in two"><%= @entry.description %></h2>
      <!-- We're here to help. Call 416-231-6555 Ext: 241. Pierre Sicco Family Lawyer -->
    </div>
  </div>
  <div class="home-footer">
    <p class="footer-text">
      ©Pierre Sicco.Disclaimer/Terms of Use | Sitemap | 5464 Dundas St. W., Suite 302 Etobicoke, ON | 416-231-6555 Ext: 241
    </p>
  </div>
</div>

app/views/location/index.html.erb
<div class="container-fluid container-map">
  <div class="row map-row">
    <div class="col-lg-6 img-top-col">
      <%= image_tag "location.jpg", :class => "img-top location-img" %>
    </div>
    <div class="col-lg-6 testimonial-text">
      <div class="fade-in one">
        <h2 class="location-text">Pierre Sicco</h2>
        <h2 class="location-text">5464 Dundas St. W., Suite 302</h2>
        <h2 class="location-text">Toronto, Ontario M9B 1B4</h3>
        <h2 class="location-text">Phone (416) 231-6555 Ext: 241</h2>
        <button type="button" class="btn btn-warning btn-lg location-button">Email Me</button>
        <h2 class="location-text"><a href="#" class="map-button"><span class="glyphicon glyphicon-map-marker" aria-hidden="true"></span></a>Map View<h2>
      </div>
    </div>
  </div>
</div>
<div class="home-footer-testimonial">
  <p class="footer-text-testimonial">
    ©Pierre Sicco.Disclaimer/Terms of Use | Sitemap | 5464 Dundas St. W., Suite 302 Etobicoke, ON | 416-231-6555 Ext: 241
  </p>
</div>
<div class="email-container">
  <div class="email-box">
    <div class="email-input">
      <%= bootstrap_form_for @email, url: create_email_path do |f| %>
        <%= f.email_field :email_address %>
        <%= f.text_field :email_subject %>
        <%= f.text_area :email_content %>
        <%= f.submit "Send email" %>
      <% end %>
    </div>
  </div>
</div>
<div class="map-container">
  <div class="map-box">
    <div id="map">

    </div>
  </div>
</div>

<script async defer
 src="https://maps.googleapis.com/maps/api/js?key=AIzaSyB08GRk2ZArZa6PeELdo-DIK6b4uhEypH8&callback=initMap">
</script>

<script type="text/javascript">
$(function() {

  var $body = $(document);
  $body.bind('scroll', function() {
      // "Disable" the horizontal scroll.
      if ($body.scrollLeft() !== 0) {
          $body.scrollLeft(0);
      }
  });

  $(".location-button").on("click", function(){
    $(".email-container").fadeIn()
    $(".email-input").on("click", function (){
      event.stopPropagation()
    });
    $(".email-box").on("click", function(){
      $(".email-container").fadeOut()
    });
  });

  $(".map-button").on("click", function(){
    $(".map-container").fadeIn()
    $("#map").on("click", function (){
      event.stopPropagation()
    });
    $(".map-box").on("click", function(){
      $(".map-container").fadeOut()
    });

    var locationLat = ""
    var locationLong = ""

    function initMap() {

    }

    $.ajax({
      url: "https://maps.googleapis.com/maps/api/geocode/json?address=" + "5464 Dundas St. W, Etobicoke, ON" + "&key=AIzaSyB08GRk2ZArZa6PeELdo-DIK6b4uhEypH8",
      dataType: "JSON",
      method: "GET"
    }).done(function(data){
      locationLat = data["results"][0]["geometry"]["location"]["lat"]
      locationLong = data["results"][0]["geometry"]["location"]["lng"]
      console.log(locationLat, locationLong)
      makeMap()
    })

    function makeMap() {

    }

    function makeMap() {
      var uluru = {lat: locationLat, lng: locationLong};
      var map = new google.maps.Map(document.getElementById('map'), {
        zoom: 13,
        center: uluru
      });

      var contentString = '<p>5464 Dundas St. W., Suite 200</p>' +
                          '<p>Toronto, Ontario M9B 1B4</p>' +
                          '<p>Phone: (416) 231-6555 Ext: 241</p>' +
                          '<p>psicco@mwlc.ca</h3>'

      var infowindow = new google.maps.InfoWindow({
        content: contentString
      });

      var marker = new google.maps.Marker({
        position: uluru,
        map: map
      });
      marker.addListener('click', function(){
        infowindow.open(map, marker);
      });
     }
  });


});
</script>