config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'home#index'
  get '/about', to: 'about#index'
  get '/area_of_practice', to: 'area_of_practice#index'
  get '/testimonials', to: 'testimonials#index'
  get '/location', to: 'location#index'
  post '/location', to: 'location#create', as: 'create_email'
  resources :users
  resources :dashboard
  resources :sessions
  resources :entries
  resources :thank_you

  post '/dashboard/handle_request', to: "dashboard#handle_request", as: "create_entry"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/email.rb
class Email < ApplicationRecord
end

app/models/entry.rb
class Entry < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  
  has_secure_password

end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
    @entry = Entry.where(category: "about")
  end
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController

  def create
    entry = Entry.new(entry_params)
    if entry.save
      redirect_to dashboard_index_url
    end
  end

  def destroy
    entry = Entry.find_by_id(params[:id])
    entry.destroy!
    redirect_to dashboard_index_url
  end

  def update
    entry = Entry.find_by_id(params[:id])
    entry.update_attributes(updated_attributes)
    redirect_to dashboard_index_url
  end


  private

  def entry_params
    params.require(:entry).permit(:title, :description, :category)
  end

  def updated_attributes
    params.require(:entry).permit(:title, :description, :category)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @entry = Entry.find_by(category: "home-page")
  end
end

app/controllers/location_controller.rb
class LocationController < ApplicationController
  def index
    @email = Email.new
  end

  def create
    @email = Email.new(email_params)
    if @email.save
      UserNotifierMailer.send_signup_email(@email).deliver
      redirect_to thank_you_index_path
      flash[:notice] = "Email succesfully sent!"
    else
      redirect_to location_url
      flash[:notice] = "Something wen't wrong, try again."
    end

  end

  private
  def email_params
    params.require(:email).permit(:email_content, :email_address, :email_subject)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def create
    user = User.find_by('lower(username) = ?', session_params[:username].downcase)
    if user && user.authenticate(session_params[:password])
      session[:user_id] = user.id
      redirect_to dashboard_index_url
    else
      redirect_to root_url
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url
  end

  private
  def session_params
    params.require(:session).permit(:username, :password)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    user = User.new(user_params)
    if user.save
      session[:user_id] = user.id
      redirect_to dashboard_index_url
    else
      redirect_to root_url
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :password, :password_confirmation)
  end

end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def css_slug
    "#{params[:controller]}-#{params[:action]}"
  end
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/location_helper.rb
module LocationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/testimonials_helper.rb
module TestimonialsHelper
end

app/helpers/thank_you_helper.rb
module ThankYouHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html class="<%= css_slug %>">
  <head>
    <title>Sicco</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= stylesheet_link_tag 'application', 'https://fonts.googleapis.com/css?family=Lato', media: 'all'  %>
    <%= javascript_include_tag 'application' %>

    <!-- NOTE: http://kenwheeler.github.io/slick/ -->
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Google Tag Manager -->
    <script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
    new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
    j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
    'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
    })(window,document,'script','dataLayer','GTM-5XC28N3');</script>
    <!-- End Google Tag Manager -->

  </head>

  <body class="<%= css_slug %>">
  <!-- Google Tag Manager (noscript) -->
  <noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-5XC28N3"
  height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
  <!-- End Google Tag Manager (noscript) -->
  <nav class="navbar navbar-inverse <%= css_slug  %> navbar-fixed-top-<%= css_slug  %>">
    <div class="container-fluid">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar" aria-expanded="false" aria-controls="navbar">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="<%= root_url %>"><%= image_tag "pirrelogo.png", :class => "img-logo" %><span class="name-logo">Pierre Sicco</span></a>
      </div>
      <div id="myNavbar" class="navbar-collapse collapse">
        <ul class="nav navbar-nav navbar-right links-<%= css_slug  %>">
          <li class="nav-item"><%= link_to "ABOUT", about_path %></li>
          <li class="nav-item"><%= link_to "AREA OF PRACTICE", area_of_practice_path %></li>
          <li class="nav-item"><%= link_to "TESTIMONIALS", testimonials_path %></li>
          <li class="nav-item"><%= link_to "CONTACT US", location_path %></li>
        </ul>
      </div>
    </div>
  </nav>
  <!--end of nav bar -->
    <%= yield %>
  </body>
</html>